### ISSUE TITLE
Fuseki not responding

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/buda-base#30]
We had today the issue of fuseki not responding using RdfConnectionFuseki.put(Model, graph), the connection being established on newcorerw/data ;

The following line appears 10s of thousands times in the logs (incident time: 2020-04-29 18:20:10): 

`[2020-04-29 18:20:10] ThriftConvert WARN  visit: Unrecognized: <RDF_StreamRow >`

followed by a full thread dump of the OpenJDK 64-Bit Server VM (25.242-b08 mixed mode)

**Comment by xristy** [comment]
@marc So far it looks to me like something has changed in the usage of Fuseki since about 24 hours ago.

I'm not sure whether the

    ThriftConvert WARN  visit: Unrecognized: <RDF_StreamRow >

Is a symptom or not. There were 17 occurrences starting 12:32:22Z and continuing in spurts up to 12:46:38Z when you requested a shutdown at 12:46.56.669Z.

Looking at the code this seems to be a benign warning of something other than a quad, triple, or prefix setting in the stream for `org.apache4.jena.riot.thrift.TRDF.visit(...)`; however, the occurrence of these warnings so near the point where you restarted is likely more than circumstantial.

The other thing that I notice are PUTs of graph/ontologySchema tat occur in some bunches:

- 2 between 10:26:51Z and 10:30:15
- 6 between 11:00:58Z and 11:29:07
- 6 between 12:22:46Z and 12:43:11

The last are just before the restart.

I'm wondering if these PUTs are leaving threads hanging somehow and the threadpool is full and things hang.

I think you've been working in this area and perhaps something has changed in the past 24 hours or so that is exacerbating things.

I don't understand the `thrift` mechanism so I don't know if there's a correlation with the PUTs but it seems possible. There are no warnings until around the same time as the last 6 PUTs of ontologySchema.

The stop produces a thread dump but I can't immediately see what threads are waiting to be used or waiting for something to finish. I can look deeper later.

In the meantime if yuou identify something that has changed with how Fuseki is being interacted w/ in the past 24 hours or so that might be helpful. Nothing has changed in ythe Fuseki deployment.

Maybe something else has changed other than ontology like a lds-query or something.

It's apparently somewhat reproducible in a few hours or so and we may see more evidence on the next restart.

**Comment by xristy** [comment]
**Summary**, at restart there seem to be several threads hung in transactions. There's a cluster of PUTs of graph/ontologySchema over 21 minutes which it would seem implausible that these are coming too fast - the ontologySchema is around 7100+ triples which doesn't seem particularly large.

@MarcAgate it could help to know what changes in ldspdi over the past 24-36 hours might be correlated with this issue which has now occurred twice in that time period and we have seen before that I'm aware. Also, is `BinaryRDF` being used for transfers?

To avoid looking at this log again here for the record is some detail on the various threads.

- first thread
>30-Apr-2020 12:46:56.938 WARNING [localhost-startStop-2] 
  org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads 
  The web application [fuseki] is still processing a request that has yet to finish. 
  This is very likely to create a memory leak. 
  You can control the time allowed for requests to finish by using the unloadDelay attribute of the standard Context implementation. 
  Stack trace of request processing thread:
```
     ...
 org.apache.jena.tdb.transaction.TransactionManager.acquireWriterLock(TransactionManager.java:616)
 org.apache.jena.tdb.transaction.TransactionManager.beginInternal(TransactionManager.java:358)
 org.apache.jena.tdb.transaction.TransactionManager.begin(TransactionManager.java:343)
 org.apache.jena.tdb.StoreConnection.begin(StoreConnection.java:128)
 org.apache.jena.tdb.StoreConnection.begin(StoreConnection.java:108)
 org.apache.jena.tdb.transaction.DatasetGraphTransaction.begin(DatasetGraphTransaction.java:169)
 org.apache.jena.tdb.transaction.DatasetGraphTransaction.begin(DatasetGraphTransaction.java:162)
 org.apache.jena.sparql.core.DatasetGraphWrapper.begin(DatasetGraphWrapper.java:237)
 org.apache.jena.query.text.DatasetGraphText.begin(DatasetGraphText.java:174)
 org.apache.jena.query.text.DatasetGraphText.begin(DatasetGraphText.java:164)
 org.apache.jena.fuseki.servlets.HttpAction.begin(HttpAction.java:280)
```
which appears to be a thread waiting to `acquireWriterLock` prior to jena.text indexing some resource

- second thread, same warning as above at `30-Apr-2020 12:46:56.940`; however, this thread is hung in:
```
    org.apache.tomcat.util.net.NioEndpoint$KeyAttachment.awaitLatch(NioEndpoint.java:1400)
```
which appears to be in the midst of reading binary rdf off of some endpoint:
```
org.apache.jena.riot.thrift.BinRDF.apply(BinRDF.java:181)
```
where is BinaryRDF being used?

- third thread is in a state w/ a SEVERE complaint
```
30-Apr-2020 12:46:56.940 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [fuseki] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@56d6d374]) and a value of type [org.apache.jena.query.ReadWrite] (value [WRITE]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
30-Apr-2020 12:46:56.941 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks Unable to determine string representation of value of type [org.apache.jena.tdb.transaction.DatasetGraphTxn]
 java.lang.UnsupportedOperationException: Transactional.begin(TxnType
        at org.apache.jena.sparql.core.TransactionalNotSupported.begin(TransactionalNotSupported.java:66)
	at org.apache.jena.tdb.store.DatasetGraphTDB.begin(DatasetGraphTDB.java:265)
        at org.apache.jena.system.Txn.calc(Txn.java:96)
        at org.apache.jena.system.Txn.calculateRead(Txn.java:120)
        at org.apache.jena.sparql.core.DatasetGraphWrapper.toString(DatasetGraphWrapper.java:211)
        at org.apache.jena.tdb.transaction.DatasetGraphTxn.toString(DatasetGraphTxn.java:71)
```

- fourth thread same as third

- fifth thread much the same as previous 2 but with an additional SEVERE
```
30-Apr-2020 12:46:56.944 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [fuseki] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@56d6d374]) and a value of type [org.apache.jena.query.ReadWrite] (value [WRITE]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
```

- sixth thread I don't understand. Looks like some sort of management thread:
```
30-Apr-2020 12:46:56.944 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [fuseki] created a ThreadLocal with key of type [java.lang.ThreadLocal.SuppliedThreadLocal] (value [java.lang.ThreadLocal$SuppliedThreadLocal@1d92b579]) and a value of type [org.apache.jena.tdb.transaction.DatasetGraphTxn] (value [Unknown]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
30-Apr-2020 12:46:56.961 INFO [main] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-13180"]
30-Apr-2020 12:46:57.043 INFO [http-nio-13180-exec-1] org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading Illegal access: this web application instance has been stopped already. Could not load [org.apache.log4j.spi.ThrowableInformation]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
 java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.log4j.spi.ThrowableInformation]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1372)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1360)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1219)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1180)
	at org.apache.log4j.spi.LoggingEvent.<init>(LoggingEvent.java:165)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.warn(Log4jLoggerAdapter.java:479)
	at org.apache.jena.atlas.logging.FmtLog.warn(FmtLog.java:113)
	at org.apache.jena.fuseki.servlets.ActionExecLib.execAction(ActionExecLib.java:124)
	at org.apache.jena.fuseki.server.Dispatcher.dispatchAction(Dispatcher.java:114)
```

Following these threads is a full thread dump. 

12 in `TIMED_WAITING (parking)` 
```
"localhost-startStop-2" #117 daemon prio=5 os_prio=0 tid=0x00007fef4800f000 nid=0x35a7 waiting on condition [0x00007fef57dfe000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006c0728fe8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

3 in `TIMED_WAITING (sleeping)` which are idle threads:
```
"ajp-nio-13109-Acceptor-0" #44 daemon prio=5 os_prio=0 tid=0x00007fefc8249800 nid=0x1946 waiting on condition [0x00007fef54e95000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:673)
	at java.lang.Thread.run(Thread.java:748)
```

A Jena daemon thread
```
"http-nio-13180-exec-9" #27 daemon prio=5 os_prio=0 tid=0x00007fefc81cb800 nid=0x1935 waiting on condition [0x00007fef55fa3000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000076ef1ea00> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at org.apache.tomcat.util.net.NioEndpoint$KeyAttachment.awaitLatch(NioEndpoint.java:1400)
	at org.apache.tomcat.util.net.NioEndpoint$KeyAttachment.awaitReadLatch(NioEndpoint.java:1402)
	at org.apache.tomcat.util.net.NioBlockingSelector.read(NioBlockingSelector.java:185)
	at org.apache.tomcat.util.net.NioSelectorPool.read(NioSelectorPool.java:250)
	at org.apache.tomcat.util.net.NioSelectorPool.read(NioSelectorPool.java:231)
	at org.apache.coyote.http11.InternalNioInputBuffer.fill(InternalNioInputBuffer.java:135)
	at org.apache.coyote.http11.InternalNioInputBuffer$SocketInputBuffer.doRead(InternalNioInputBuffer.java:178)
	at org.apache.coyote.http11.filters.IdentityInputFilter.doRead(IdentityInputFilter.java:110)
	at org.apache.coyote.http11.AbstractInputBuffer.doRead(AbstractInputBuffer.java:368)
	at org.apache.coyote.Request.doRead(Request.java:476)
	at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:344)
	at org.apache.tomcat.util.buf.ByteChunk.checkEof(ByteChunk.java:361)
	at org.apache.tomcat.util.buf.ByteChunk.substract(ByteChunk.java:343)
	at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:369)
	at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:190)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	- locked <0x0000000789223d68> (a java.io.BufferedInputStream)
	at org.apache.thrift.transport.TIOStreamTransport.read(TIOStreamTransport.java:127)
	at org.apache.thrift.transport.TTransport.readAll(TTransport.java:86)
	at org.apache.thrift.protocol.TCompactProtocol.readByte(TCompactProtocol.java:637)
	at org.apache.thrift.protocol.TCompactProtocol.readFieldBegin(TCompactProtocol.java:543)
	at org.apache.thrift.TUnion$TUnionStandardScheme.read(TUnion.java:222)
	at org.apache.thrift.TUnion$TUnionStandardScheme.read(TUnion.java:213)
	at org.apache.thrift.TUnion.read(TUnion.java:138)
	at org.apache.jena.riot.thrift.BinRDF.apply(BinRDF.java:181)
	at org.apache.jena.riot.thrift.BinRDF.applyVisitor(BinRDF.java:170)
```
evidently associated with BinaryRDF transfers

The rest of the threads are Tomcat and JVM system threads, like servlet polling, GC and so on.

**Comment by xristy** [comment]
The problem occurred again at `[2020-06-30 14:12:53]`
```
[2020-06-30 14:10:40] Admin      INFO  [120602] GET http://buda1.bdrc.io:13180/fuseki/$/metrics
[2020-06-30 14:10:40] Admin      INFO  [120602] 200 OK (1 ms)
[2020-06-30 14:11:10] Admin      INFO  [120603] GET http://buda1.bdrc.io:13180/fuseki/$/metrics
[2020-06-30 14:11:10] Admin      INFO  [120603] 200 OK (1 ms)
[2020-06-30 14:11:40] Admin      INFO  [120604] GET http://buda1.bdrc.io:13180/fuseki/$/metrics
[2020-06-30 14:11:40] Admin      INFO  [120604] 200 OK (1 ms)
[2020-06-30 14:12:10] Admin      INFO  [120605] GET http://buda1.bdrc.io:13180/fuseki/$/metrics
[2020-06-30 14:12:10] Admin      INFO  [120605] 200 OK (1 ms)
[2020-06-30 14:12:40] Admin      INFO  [120606] GET http://buda1.bdrc.io:13180/fuseki/$/metrics
[2020-06-30 14:12:40] Admin      INFO  [120606] 200 OK (1 ms)
[2020-06-30 14:12:45] Fuseki     INFO  [120607] GET http://buda1.bdrc.io:13180/fuseki/corerw?graph=http%3A%2F%2Fpurl.bdrc.io%2Fgraph%2FauthData
[2020-06-30 14:12:45] Fuseki     INFO  [120607] 200 OK (196 ms)
[2020-06-30 14:12:46] Fuseki     INFO  [120608] GET http://buda1.bdrc.io:13180/fuseki/authrw/?query=construct+%7B++%3Fs+%3Chttp%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fext%2Fuser%2FhasUserProfile%3E+%3Fpr.+%3Fs+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23prefLabel%3E+%3Flabel.+%7D+where+%7B+%7B+%3Fs+%3Fp+%3Fo.+%3Fs+a+%3Chttp%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fext%2Fuser%2FUser%3E.+%3Fs+%3Chttp%3A%2F%2Fpurl.bdrc.io%2Fontology%2Fext%2Fuser%2FhasUserProfile%3E+%3Fpr.+%3Fs+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23prefLabel%3E+%3Flabel.+%7D%7D
[2020-06-30 14:12:46] Fuseki     INFO  [120608] Query = construct {  ?s <http://purl.bdrc.io/ontology/ext/user/hasUserProfile> ?pr. ?s <http://www.w3.org/2004/02/skos/core#prefLabel> ?label. } where { { ?s ?p ?o. ?s a <http://purl.bdrc.io/ontology/ext/user/User>. ?s <http://purl.bdrc.io/ontology/ext/user/hasUserProfile> ?pr. ?s <http://www.w3.org/2004/02/skos/core#prefLabel> ?label. }}
[2020-06-30 14:12:46] Fuseki     INFO  [120608] 200 OK (1 ms)
[2020-06-30 14:12:47] Fuseki     INFO  [120609] POST http://buda1.bdrc.io:13180/fuseki/corerw/query
[2020-06-30 14:12:47] Fuseki     INFO  [120609] Query = PREFIX  :     <http://purl.bdrc.io/ontology/core/> PREFIX  bdan: <http://purl.bdrc.io/annotation/> PREFIX  aut:  <http://purl.bdrc.io/ontology/ext/auth/> PREFIX  bf:   <http://id.loc.gov/ontologies/bibframe/> PREFIX  tbr:  <http://purl.bdrc.io/ontology/toberemoved/> PREFIX  owl:  <http://www.w3.org/2002/07/owl#> PREFIX  rsh:  <http://purl.bdrc.io/shacl/core/shape/> PREFIX  bdou: <http://purl.bdrc.io/ontology/ext/user/> PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#> PREFIX  skos: <http://www.w3.org/2004/02/skos/core#> PREFIX  bdac: <http://purl.bdrc.io/anncollection/> PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX  wd:   <http://www.wikidata.org/entity/> PREFIX  srcpe: <https://sakyaresearch.org/persons/> PREFIX  oa:   <http://www.w3.org/ns/oa#> PREFIX  mbbt: <http://mbingenheimer.net/tools/bibls/> PREFIX  bdgup: <http://purl.bdrc.io/graph-nc/user-private/> PREFIX  sh:   <http://www.w3.org/ns/shacl#> PREFIX  dila: <http://purl.dila.edu.tw/resource/> PREFIX  tmp:  <http://purl.bdrc.io/ontology/tmp/> PREFIX  dcterms: <http://purl.org/dc/terms/> PREFIX  text: <http://jena.apache.org/text#> PREFIX  foaf: <http://xmlns.com/foaf/0.1/> PREFIX  bda:  <http://purl.bdrc.io/admindata/> PREFIX  bdgu: <http://purl.bdrc.io/graph-nc/user/> PREFIX  bdg:  <http://purl.bdrc.io/graph/> PREFIX  ola:  <https://openlibrary.org/authors/> PREFIX  srct: <https://sakyaresearch.org/topics/> PREFIX  f:    <java:io.bdrc.ldspdi.sparql.functions.> PREFIX  srcpl: <https://sakyaresearch.org/places/> PREFIX  adm:  <http://purl.bdrc.io/ontology/admin/> PREFIX  vcard: <http://www.w3.org/2006/vcard/ns#> PREFIX  bdo:  <http://purl.bdrc.io/ontology/core/> PREFIX  iiif2: <http://iiif.io/api/presentation/2#> PREFIX  adr:  <http://purl.bdrc.io/resource-nc/auth/> PREFIX  iiif3: <http://iiif.io/api/presentation/3#> PREFIX  viaf: <http://viaf.org/viaf/> PREFIX  bds:  <http://purl.bdrc.io/ontology/shapes/core/> PREFIX  eftr: <http://purl.84000.co/resource/core/> PREFIX  bdr:  <http://purl.bdrc.io/resource/> PREFIX  as:   <http://www.w3.org/ns/activitystreams#> PREFIX  bdu:  <http://purl.bdrc.io/resource-nc/user/> PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX  srcd: <https://sakyaresearch.org/deities/> PREFIX  ldp:  <http://www.w3.org/ns/ldp#> PREFIX  srcs: <https://sakyaresearch.org/sources/> PREFIX  srcl: <https://sakyaresearch.org/literary_forms/>  CONSTRUCT    {      ?super :taxHasSubClass ?sub .     ?sub skos:prefLabel ?subl .   } WHERE   {   { bdr:O9TAXTBRC201605 (:taxHasSubClass)+ ?sub .         ?super  :taxHasSubClass  ?sub .         ?sub    skos:prefLabel   ?subl       }     UNION       { bdr:O9TAXTBRC201605                   skos:prefLabel  ?subl         BIND(bdr:O9TAXTBRC201605 AS ?sub)       }   } 
[2020-06-30 14:12:48] Fuseki     INFO  [120609] 200 OK (1.256 s)
[2020-06-30 14:12:50] Fuseki     INFO  [120610] GET http://buda1.bdrc.io:13180/fuseki/corerw?graph=http%3A%2F%2Fpurl.bdrc.io%2Fgraph%2FauthData
[2020-06-30 14:12:50] Fuseki     INFO  [120610] 200 OK (8 ms)
[2020-06-30 14:12:51] Fuseki     INFO  [120611] PUT http://buda1.bdrc.io:13180/fuseki/corerw/data?graph=http://purl.bdrc.io/graph/PersonUIShapes
[2020-06-30 14:12:52] Fuseki     INFO  [120612] PUT http://buda1.bdrc.io:13180/fuseki/corerw/data?graph=http://purl.bdrc.io/graph/ontologySchema
[2020-06-30 14:12:53] Fuseki     INFO  [120611] Body: Content-Length=73984, Content-Type=application/rdf+thrift, Charset=null => RDF-THRIFT : Count=839 Triples=839 Quads=0
[2020-06-30 14:12:53] Fuseki     INFO  [120611] 200 OK (2.106 s)
[2020-06-30 14:12:57] ThriftConvert WARN  visit: Unrecognized: <RDF_StreamRow >
[2020-06-30 14:12:57] ThriftConvert WARN  visit: Unrecognized: <RDF_StreamRow >
[2020-06-30 14:12:57] ThriftConvert WARN visit: Unrecognized: <RDF_StreamRow >
[2020-06-30 14:12:57] ThriftConvert WARN visit: Unrecognized: <RDF_StreamRow >
[2020-06-30 14:12:57] ThriftConvert WARN visit: Unrecognized: <RDF_StreamRow >
```
from then until 16:21:33 when fuseki was restarted there were some 198M occurrences and essentially as far as I can tell fuseki was unresponsive at least to further PUTs.

About 13 minutes earlier there was some activity that looks like ldspdi maybe restarting:
```
[2020-06-30 13:59:45] Fuseki INFO [120566] Body: Content-Length=34079, Content-Type=application/rdf+thrift, Charset=null => RDF-THRIFT : Count=362 Triples=362 Quads=0
[2020-06-30 13:59:45] Fuseki INFO [120566] 200 OK (97 ms)
[2020-06-30 13:59:45] Fuseki INFO [120567] PUT http://buda1.bdrc.io:13180/fuseki/corerw/data?graph=http://purl.bdrc.io/graph/PersonUIShapes
[2020-06-30 13:59:45] Fuseki INFO [120567] Body: Content-Length=73984, Content-Type=application/rdf+thrift, Charset=null => RDF-THRIFT : Count=839 Triples=839 Quads=0
[2020-06-30 13:59:46] Fuseki INFO [120567] 200 OK (140 ms)
[2020-06-30 13:59:46] Fuseki INFO [120568] PUT http://buda1.bdrc.io:13180/fuseki/corerw/data?graph=http://purl.bdrc.io/graph/PersonLocalShapes
[2020-06-30 13:59:46] Fuseki INFO [120568] Body: Content-Length=39724, Content-Type=application/rdf+thrift, Charset=null => RDF-THRIFT : Count=429 Triples=429 Quads=0
[2020-06-30 13:59:46] Fuseki INFO [120569] PUT http://buda1.bdrc.io:13180/fuseki/corerw/data?graph=http://purl.bdrc.io/graph/ontologySchema
[2020-06-30 13:59:46] Fuseki INFO [120568] 200 OK (98 ms)
[2020-06-30 13:59:46] Fuseki INFO [120570] PUT http://buda1.bdrc.io:13180/fuseki/corerw/data?graph=http://purl.bdrc.io/graph/ItemShapes
[2020-06-30 13:59:46] Fuseki INFO [120569] Body: Content-Length=683128, Content-Type=application/rdf+thrift, Charset=null => RDF-THRIFT : Count=7576 Triples=7576 Quads=0
[2020-06-30 13:59:46] Fuseki INFO [120569] 200 OK (676 ms)
[2020-06-30 13:59:46] Fuseki INFO [120571] PUT http://buda1.bdrc.io:13180/fuseki/corerw/data?graph=http://purl.bdrc.io/graph/authSchema
[2020-06-30 13:59:46] Fuseki INFO [120570] Body: Content-Length=33849, Content-Type=application/rdf+thrift, Charset=null => RDF-THRIFT : Count=359 Triples=359 Quads=0
[2020-06-30 13:59:46] Fuseki INFO [120570] 200 OK (721 ms)
```
It may be of interest that the PUT of `PersonUIShapes` at 14:12:51 overlaps with the PUT of `ontologySchema` at 14:12:52. The transfer of `PersonUIShapes` completed at 14:12:53 and the sender was sent `200 OK (2.106 s)` at 14:12:53.

There were also a few queries involving `authData` a few seconds earlier and some metrics GETs, but no other PUTs such as in the snippet from around 13:59:46

**Comment by xristy** [comment]
The problem was noticed because git-todbs hung just as it started a transfer of ontologySchema (7536 triples) at 15:46:59 from buda2 to fuseki on buda1.

The rate of the `ThriftConvert WARN` messages was around 20-26K per second. Leading to 199M line catalina.out of 15.93GB.

A message to users@jena will be sent

**Comment by xristy** [comment]
@MarcAgate prepared a full catalina.out from 2020-06-30 w/o the `ThriftConvert WARN` messages.

[catalina.out.all-20200630-stripped.txt.zip](https://github.com/buda-base/buda-base/files/4859207/catalina.out.all-20200630-stripped.txt.zip)

The failure starts at 2020-06-30 14:12:51 line# 11305

and extends to the stacktraces resulting from the “systemctl restart fuseki.service” begin at 30-Jun-2020 16:21:28.445 line# 12940 to the startup at 30-Jun-2020 16:21:34.866 line# 18856
